# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:
  app: # Имя сервиса
    image: djecka/devops-for-programmers-project-74
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-username}
      DATABASE_NAME: ${DATABASE_NAME:-name}
    depends_on:
      - db
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
    # Команда, которая будет выполнена после старта сервиса
    command: bash -c 'sleep 3 && npm test'
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_USER: ${DATABASE_USERNAME:-username}
      POSTGRES_DB: ${DATABASE_NAME:-name}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
