version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
    command: bash -c 'sleep 10 && npm start'
    ports: # Проброс портов
      - "8080:8080"

  caddy:
    image: caddy:2
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile