version: "3"
services:
  app: # Имя сервиса
    build:
      dockerfile: Dockerfile.production
    command: npm run dev
    ports: # Проброс портов
      - "8080:8080"
    volumes:
      # Текущая директория пробрасывается в директорию /app внутри контейнера
      # Путь внутри контейнера (после двоеточия) обязательно должен быть абсолютным
      - "./app:/app"