name: hexlet-push
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v3

      # Устанавливаем Node.js
      - uses: actions/setup-node@v1

      # Ставим зависимости
      - run: cd app && npm install
      - run: cd app && npm ci

      - run: docker-compose -f docker-compose.yml up --abort-on-container-exit
      - run: docker-compose -f docker-compose.yml build app
      - run: docker-compose -f docker-compose.yml push app